import { z } from 'zod'

export const vendedorSchema = z.object({
  nome: z.string().min(1, 'Obrigatório'),
  cpf_cnpj: z.string().optional().nullable(),
  rg: z.string().optional().nullable(),
  data_nascimento: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  email_corporativo: z.string().optional().nullable(),
  telefone: z.string().optional().nullable(),
  telefone_secundario: z.string().optional().nullable(),
  whatsapp: z.string().optional().nullable(),
  tipo_vinculo: z.string().optional().nullable(),
  tipo_mercado: z.string().optional().nullable(),
  comissao_interna: z.coerce.number().optional().nullable(),
  comissao_exportacao: z.coerce.number().optional().nullable(),
  comissao_fixa: z.coerce.number().optional().nullable(),
  meta_mensal: z.coerce.number().optional().nullable(),
  frequencia_pagamento: z.string().optional().nullable(),
  moeda_padrao: z.string().optional().nullable(),
  regioes_atuacao: z.string().optional().nullable(),
  paises_atuacao: z.string().optional().nullable(),
  banco_nome: z.string().optional().nullable(),
  agencia: z.string().optional().nullable(),
  conta: z.string().optional().nullable(),
  tipo_conta: z.string().optional().nullable(),
  chave_pix_tipo: z.string().optional().nullable(),
  chave_pix: z.string().optional().nullable(),
  cep: z.string().optional().nullable(),
  logradouro: z.string().optional().nullable(),
  numero: z.string().optional().nullable(),
  bairro: z.string().optional().nullable(),
  cidade: z.string().optional().nullable(),
  estado: z.string().optional().nullable(),
  status: z.string().default('ativo'),
})
export type VendedorFormValues = z.infer<typeof vendedorSchema>
